/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-07-23 17:42:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.transfer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class transfer3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1626059103590L));
    _jspx_dependants.put("jar:file:/C:/kopo/kopo-05-web/server-work/wtpwebapps/HN-OpenBanking/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/kopo/kopo-05-web/server-work/wtpwebapps/HN-OpenBanking/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/kopo/kopo-05-web/server-work/wtpwebapps/HN-OpenBanking/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("	\r\n");
      out.write("	    let holder = $('#holder').val()\r\n");
      out.write("	    let msg = $('#msg').val()\r\n");
      out.write("		\r\n");
      out.write("	    \r\n");
      out.write("		// 계좌 주가 존재하면?\r\n");
      out.write("		if(holder){\r\n");
      out.write("			$('#ajaxTest03').css(\"display\", \"block\")\r\n");
      out.write("			$('#bank_code').attr('disabled', true)\r\n");
      out.write("			$('#account_num').attr('readonly', true)\r\n");
      out.write("			$('#amount').attr('readonly', true)\r\n");
      out.write("			$('#secondStepBtn').css(\"visibility\", \"hidden\")\r\n");
      out.write("		}\r\n");
      out.write("	    // 계좌 주가 존재하지 않으면\r\n");
      out.write("		else{\r\n");
      out.write("			$('#alert-modal-body-msg').text(msg)\r\n");
      out.write("			$('#alertModal').modal('show')\r\n");
      out.write("		}\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("function nextStep03(){\r\n");
      out.write("	\r\n");
      out.write("	accountPw = $('#account_pw').val()\r\n");
      out.write("	\r\n");
      out.write("	console.log(accountPw)\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url : \"");
      out.print(request.getContextPath());
      out.write("/transfer3.do\",\r\n");
      out.write("		data : {\r\n");
      out.write("			acnt : account,\r\n");
      out.write("			account_pw : accountPw,\r\n");
      out.write("		},\r\n");
      out.write("		type : \"post\",\r\n");
      out.write("		success : callback,\r\n");
      out.write("		error : function() {\r\n");
      out.write("			alert('error')\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<input type=\"hidden\" id=\"msg\" name=\"msg\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"holder\" name=\"holder\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${holder }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("				<section id=\"ajaxTest03\" hidden>\r\n");
      out.write("					<h3 id=\"elements\">3단계 : 비밀번호 입력</h3>\r\n");
      out.write("					<p>해당 계좌의 비밀번호를 입력해주세요.</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<hr class=\"major\" />\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-4 col-12-xsmall\">\r\n");
      out.write("								<div class=\"col-12\">\r\n");
      out.write("									<h4>계좌 비밀번호</h4>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"col-12\">\r\n");
      out.write("									<input type=\"password\" name=\"account_pw\" id=\"account_pw\" value=\"\"\r\n");
      out.write("										placeholder=\"상대방 계좌번호를 입력하세요(하이픈 포함)\" />\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<!-- Break -->\r\n");
      out.write("							<div class=\"col-12\" style=\"text-align: right; margin-top: 2em\">\r\n");
      out.write("								<input type=\"button\" value=\"다음\" class=\"button primary large\"\r\n");
      out.write("									onclick=\"nextStep03()\" />\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("				</section>\r\n");
      out.write("\r\n");
      out.write("	");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
