-- DB링크 연결


/* HN은행 */
CREATE DATABASE LINK "HN_BANK" CONNECT TO da2102 IDENTIFIED BY "da02" USING
'(DESCRIPTION=
 (ADDRESS_LIST=
  (ADDRESS=(PROTOCOL=TCP)(HOST=192.168.217.202)(PORT=1521))
 )
 (CONNECT_DATA=
 (SERVICE_NAME=KOPODA)
 )
)';

/* YB */
CREATE DATABASE LINK "YB_BANK" CONNECT TO da2110 IDENTIFIED BY "da2110" USING
'(DESCRIPTION=
 (ADDRESS_LIST=
  (ADDRESS=(PROTOCOL=TCP)(HOST=192.168.217.202)(PORT=1521))
 )
 (CONNECT_DATA=
 (SERVICE_NAME=KOPODA)
 )
)'; 

/* BANKER */
CREATE DATABASE LINK "BANKER_BANK" CONNECT TO da2111 IDENTIFIED BY "da11" USING
'(DESCRIPTION=
 (ADDRESS_LIST=
  (ADDRESS=(PROTOCOL=TCP)(HOST=192.168.217.202)(PORT=1521))
 )
 (CONNECT_DATA=
 (SERVICE_NAME=KOPODA)
 )
)'; 

/* CM-BANK */
CREATE DATABASE LINK "CM_BANK" CONNECT TO da2104 IDENTIFIED BY "da04" USING
'(DESCRIPTION=
 (ADDRESS_LIST=
  (ADDRESS=(PROTOCOL=TCP)(HOST=192.168.217.202)(PORT=1521))
 )
 (CONNECT_DATA=
 (SERVICE_NAME=KOPODA)
 )
)'; 